 version: '3.8'
 services:
   app:
       build:
         context: .
         dockerfile: Dockerfile
       volumes:
         - '.:/var/www/html'
       ports:
         - '9000:9000'
       environment:
          - DB_CONNECTION=mysql
          - DB_HOST=db
          - DB_PORT=3306
          - DB_DATABASE=ecommerce_db
          - DB_USERNAME=root
          - DB_PASSWORD=root
       depends_on:
         - db
         - redis

   db:
       image: mysql:8
       ports:
           - '3306:3306'
       environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: ecommerce_db
       volumes:
         - mysql_data:/var/lib/mysql
   redis:
         image: redis:alpine
         ports:
           - '6379:6379'

 volumes:
   mysql_data: